### PR TITLE
Enforce Terms of Service on the Apply Page

### LINKED ISSUE #187: Bug: Users Can Submit Apply to Contribute form without agreeing to the Terms and Conditions
**Describe the bug**
You can apply to be a contributor without agreeing to the terms and conditions if you check the second box (would like a team member from 7000 Languages to follow up...) We should update the form validation that occurs in `client/src/pages/Apply `by not including the second checkbox in the form validation.

### PR DESCRIPTION
**Pull request by exrlla**
## Status:
:rocket: Ready

### Description
Now allows contributors to create a course and submit the application iff they agree to the Terms of Service. 

Fixes #187 

## Screenshots
IMG_7662

### CODE REVIEW

**Review by ashayp22 — CHANGES_REQUESTED** [review]
@exrlla Are users now able to submit the form without clicking the Terms of Service checkbox? Before, the issue was that users could submit the form by clicking the first or second checkbox. We need users to be able to submit a course only if they have clicked the Terms of Service checkbox. It doesn't matter if the first or second checkbox is selected.

See #187 for more details.

File: client/src/pages/Apply/Apply.js [hunk 1]
```diff
@@ -95,13 +96,16 @@ const Apply = ({ navigation }) => {
...
+      validateErrors.followUp = 'Follow up is required'
+    }
     setErrors(validateErrors)
 
     return Object.keys(validateErrors).length === 0
   }
 
   // Confirms validation of course for pressing 'Submit'
-  const areAllFilled = name !== '' && email !== '' && language !== '' && acceptTerms
+  const areAllFilled = (name !== '' && email !== '' && language !== '' && acceptTerms ) || (name !== '' && email !== '' && language !== '' && followUp)
```
Comment (ashayp22) [inline client/src/pages/Apply/Apply.js:108]: change to only allowing accept terms

**Review by ashayp22 — COMMENTED** [review]
glhf

**Review by rustom — APPROVED** [review]
LGTM!!!!! ❤️

File: client/src/pages/Apply/Apply.js [hunk 2]
```diff
@@ -95,13 +96,16 @@ const Apply = ({ navigation }) => {
     if (acceptTerms === false) {
       validateErrors.acceptTerms = 'Terms are required'
     }
```
Comment (ashayp22) [inline client/src/pages/Apply/Apply.js:98]: Will need to remove this since it doesn't matter if the followUp is checked or now. I would also suggest updating the conditional statements above so they don't check `someExpression === false`. `!someExpression` is better syntax.

Comment (ashayp22) [reply client/src/pages/Apply/Apply.js:98]: Actually, ignore this comment - see the comment below.

File: client/src/pages/Apply/Apply.js [hunk 3]
```diff
@@ -95,13 +96,16 @@ const Apply = ({ navigation }) => {
...
+    if (followUp === false) {
+      validateErrors.followUp = 'Follow up is required'
+    }
     setErrors(validateErrors)
```
Comment (ashayp22) [inline client/src/pages/Apply/Apply.js:102]: It looks like the state variable `errors` is no longer being used. Hence, all code related to the state variable `errors` should be removed because we don't want unnecessary code in the repo.

Also, it looks like `areRequiredFieldsFilled` achieves the same functionality as `validate()`. So, better off to just delete `validate()` and replace its use with `areRequiredFieldsFilled`.

File: client/src/pages/Apply/Apply.js [hunk 4]
```diff
@@ -477,17 +462,12 @@ const Apply = ({ navigation }) => {
               </View>
 
               <View style={styles.checkboxes}>
```
Comment (ashayp22) [inline client/src/pages/Apply/Apply.js:464]: I'd also recommend merging this branch with dev, and then using Jamie's custom `<RequiredField/>` component to mark all required fields. See the Create Lesson Drawer or Create Unit Drawer for examples on how to use the `<RequiredField/>` component.

**Review by ashayp22 — CHANGES_REQUESTED** [review]
Left some inline comments regarding cleaning up the `Apply.js` file.

File: client/src/pages/Apply/Apply.js [hunk 5]
```diff
@@ -123,6 +102,7 @@ const Apply = ({ navigation }) => {
         description,
         iso: isoCode,
         glotto: glottoCode,
+        followUp,
```
Comment (ashayp22) [inline client/src/pages/Apply/Apply.js:105]: Nice, you added followUp to the `courseDetails`? Can you update our API so it saves this data in MongoDB. I believe you only need to update `api/src/models/language.js` by adding the followUp field to the `CourseDetails` Mongoose schema.

File: client/src/pages/Apply/Apply.js [hunk 6]
```diff
@@ -153,7 +133,7 @@ const Apply = ({ navigation }) => {
   }
 
   const onSubmit = async () => {
-    if (validate() === true) {
+    if (areRequiredFieldsFilled === true) {
```
Comment (ashayp22) [inline client/src/pages/Apply/Apply.js:136]: No need to check if `areRequiredFieldsFilled` is true since `onSubmit()` won't be called unless the button is enabled, and if the button is enabled, then `areRequiredFieldsFilled` will always be true.

File: client/src/pages/Apply/Apply.js [hunk 7]
```diff
@@ -205,15 +185,10 @@ const Apply = ({ navigation }) => {
                     returnKeyType="done"
                     onChangeText={(text) => setName(text)}
                   />
-                  {'name' in errors ? (
-                    <FormControl.ErrorMessage>
-                      Required.
-                    </FormControl.ErrorMessage>
-                  ) : null}
                 </View>
               </FormControl>
```
Comment (ashayp22) [inline client/src/pages/Apply/Apply.js:190]: It looks like you are doing `<FormControl> <Input/> <FormControl>  <FormControl> <Input/> <FormControl/>`. What if you merge the two form controls into `<FormControl> <Input/> <Input/>  <FormControl>`

**Review by ashayp22 — CHANGES_REQUESTED** [review]
Looks good, I left a few inline comments.

File: client/src/pages/Apply/Apply.js (hunk 6 above)
Comment (exrlla) [reply client/src/pages/Apply/Apply.js:136]: This makes sense, thanks.

**Review by ashayp22 — APPROVED** [review]
