### PR TITLE
Fix Checkbox Text

### LINKED ISSUE #182: Checkbox text on Apply to Contribute page slightly goes off the screen
**Describe the bug**
Checkbox text on Apply to Contribute page slightly goes off the screen (iPhone XR).

IMG_7779

### PR DESCRIPTION
**Pull request by exrlla**
Status: 🚀 
Fixes #182

### CODE REVIEW

**Review by ashayp22 — COMMENTED** [review]
Was the change that we worked on during dev night pushed?

File: client/src/pages/Apply/Apply.js [hunk 1]
```diff
@@ -101,7 +101,7 @@ const Apply = ({ navigation }) => {
   }
 
   // Confirms validation of course for pressing 'Submit'
-  const areAllFilled = name !== '' && email !== '' && language !== '' && acceptTerms
+  // const areAllFilled = name !== '' && email !== '' && language !== '' && acceptTerms
```
Comment (ashayp22) [inline client/src/pages/Apply/Apply.js:104]: make sure to keep this validation in for now

File: client/src/pages/Apply/Apply.js [hunk 2]
```diff
@@ -443,78 +443,60 @@ const Apply = ({ navigation }) => {
                   />
                 </View>
               </FormControl>
+
               <View style={styles.checkboxes}>
```
Comment (ashayp22) [inline client/src/pages/Apply/Apply.js:447]: On my phone, the Checkbox text doesn't wrap and it goes off the screen. I also don't see the code that fixed this two dev nights ago, which was setting `styles.checkboxes.width` to `95%` (unless you had another fix).

**Review by ashayp22 — CHANGES_REQUESTED** [review]
Not sure if the bug fix wasn't pushed, but on my phone the Checkbox text still goes off the screen.

**Review by ashayp22 — APPROVED** [review]
:)
