### PR TITLE
UI Fix on Apply to Contribute

### LINKED ISSUE #228: UI Fix on Apply to Contribute
**Goals**

Screen Shot 2022-10-12 at 11 16 34 PM

On our Apply to Contribute Page, we need to move a few components around at the bottom of the page:

1. Make sure that the start of the "I would like a team member...." is inline with the checkbox.
2. Move the "By selecting this button...." right below the two checkboxes. So, it should be a part of the `ScrollView` on that Apply to Contribute Page.

### PR DESCRIPTION
**Pull request by rustom**
## Description

Pushes in the permission disclaimer and aligns the text from the button checkbox on the new contributor page.

Fixes #228.

### CODE REVIEW

File: client/src/pages/Apply/Apply.js [hunk 1]
```diff
@@ -447,59 +450,55 @@ const Apply = ({ navigation }) => {
...
+                variant="primary"
+                onPress={onSubmit}
+              />
+              <Text
+                fontFamily="body"
+                fontWeight="regular"
+                color="gray.medium"
+                fontStyle="normal"
+                fontSize="sm"
+              >
```
Comment (ashayp22) [inline client/src/pages/Apply/Apply.js:494]: Can you move this text (By selecting this button, you confirm...) above the button to match the Figma designs?

**Review by ashayp22 — CHANGES_REQUESTED** [review]

File: client/src/pages/Apply/Apply.js (hunk 1 above)
Comment (rustom) [reply client/src/pages/Apply/Apply.js:489]: done

**Comment by rustom** [comment]
the second checkbox has been removed !!!!!!!!

**Review by ashayp22 — APPROVED** [review]
