### PR TITLE
Fix language schema

### LINKED ISSUE #83: Update Language Schemas
**Goals**

Based on some product/design changes, we are going to have to make some changes to the Language Schemas.

**Course**

No changes.

**CourseDetails**

- Change `language_name` to `name`
- Change `language_description` to `description`
- Remove `population_size`
- Add a field called `translated_language (String)`. This field specifies which language the Course is translated to (for example: English).
- Add a field called `'location (String).' `This indicates where the language behind the course is spoken.
- Add a field called `'iso (String).'` This indicates the [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3) of the language.

**Units**

- Make `_order` unique.
- Add a `description` field

**Lessons**

- Make `_order ` unique.
- Add a `description` field

**Vocab**

- Add a field called `notes (String)`.

### PR DESCRIPTION
**Pull request by nroy20**
## Description

Made requested updates to certain fields in Language schema models based on product/design changes.

Fixes #83

### CODE REVIEW

File: api/src/models/language.js [hunk 1]
```diff
@@ -15,29 +17,32 @@ const Course = new mongoose.Schema({
...
   image: { type: String, required: false, default: '' },
   audio: { type: String, required: false, default: '' },
+  notes: { type: String, required: true, default: '' },
 });
 
 Vocab.index({ _order: 1 });
 
 const Lesson = new mongoose.Schema({
-  _course_id: { type: String, required: true, index: true },
+  _course_id: { type: String, required: true, index: true, unique: true },
```
Comment (ashayp22) [inline api/src/models/language.js:39]: should not be unique

**Review by ashayp22 — CHANGES_REQUESTED** [review]
fantabulous

**Review by ashayp22 — APPROVED** [review]
glorious 😵
