### PR TITLE
Removed black drop shadow on buttons and standardized button press ef…

### LINKED ISSUE #185: Back Icon turns black on Become a Contributor
**Describe the bug**
The Back Icon turns black on the Become a Contributor page. The background should be transparent or match the tab bar color (in this case, white).

Getting started: take a look at `client/src/navigator/Stacks/BackButton.js.` We'll most likely have to change something in there.

IMG_7780

### PR DESCRIPTION
**Pull request by masgras2**
## Status:
Complete

## Description
Set underlay color on all menu buttons to semi-transparent to remove black backgrounds when pressed
Fixes #185 

## Screenshots
image

### CODE REVIEW

File: client/src/navigator/Drawer/DrawerMenu.js [hunk 1]
```diff
@@ -47,12 +47,13 @@ const DrawerMenu = ({ navigation }) => (
...
-    <View style={styles.head}>
+    <View>
       <FontIcon.Button
         name="times"
-        size={20}
+        size={25}
         color={colors.gray.dark}
-        backgroundColor="white"
+        backgroundColor={"transparent"}
+        underlayColor={"#00000020"}
```
Comment (ashayp22) [inline client/src/navigator/Drawer/DrawerMenu.js:56]: I'd suggest moving the "#00000020" color to `client/theme/colors.js`. You can make it a variant of gray.

File: client/src/navigator/Stacks/BackButton.js [hunk 2]
```diff
@@ -21,6 +21,7 @@ const BackButton = ({ navigation, color, onPress }) => {
       color={color}
       size={25}
       backgroundColor="transparent"
+      underlayColor={"#00000020"}
```
Comment (ashayp22) [inline client/src/navigator/Stacks/BackButton.js:24]: See above

**Review by ashayp22 — CHANGES_REQUESTED** [review]
Overall great work on the button fix!

File: client/src/theme/colors.js [hunk 3]
```diff
@@ -21,6 +21,7 @@ const colors = {
     dark: '#C0D152', // 500 opacity
   },
   gray: {
+    semi_transparent: '#00000020', // [TODO: put opacity here]
```
Comment (ashayp22) [inline client/src/theme/colors.js:24]: once you have this in, this looks ready to merge

**Review by ashayp22 — APPROVED** [review]
Looks great!
