### PR TITLE
Landing page tablet positioning

### LINKED ISSUE #226: Bug: Landing Page Content is off-center on iPads
**Describe the bug**

On iPads, the positioning of the quotes and button is different from the designs.

**Expected behavior**

- The quote should be in one line, instead of wrapped into 3 lines. Double check with Madion and Jocylen on how the quote should look on larger tablets.
- The text and logo on the button should be centered.

**Screenshots**
Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2022-10-09 at 15 40 57

**Environment (please complete the following information):**
 - Device: iPad Pro 12.9 inch
 - OS: 15

### PR DESCRIPTION
**Pull request by rustom**
## Description

Fixes #226

### CODE REVIEW

File: client/src/pages/Landing/Landing.js [hunk 1]
```diff
@@ -91,49 +84,48 @@ const Landing = () => {
     })
   }
 
+  const window = useWindowDimensions()
+
   return (
     <View style={styles.root}>
       <Image
         source={images.background_landing}
+        alt="Language names background image"
```
Comment (ashayp22) [inline client/src/pages/Landing/Landing.js:93]: I think this alt could be improved. I know that that this app doesn't stress accessibility as much as Brink, but it would be nice to be clear when we can. Maybe an alt like, "7000 Languages red background with names of endangered languages." What do you think?

**Review by ashayp22 — CHANGES_REQUESTED** [review]
The landing page looks good on iPad 12.9 and mini, iPhone SE, and iPhone 13 Max Pro. I left one inline comment.

File: client/src/pages/Landing/Landing.js (hunk 1 above)
Comment (rustom) [reply client/src/pages/Landing/Landing.js]: agreed, fixed

**Review by ashayp22 — APPROVED** [review]
